Class {
	#name : 'AOC2025Day6Test',
	#superclass : 'TestCase',
	#category : 'AdventCode2025',
	#package : 'AdventCode2025'
}

{ #category : 'tests' }
AOC2025Day6Test >> testSolution1Part1 [
	self assert: (((AOC2025Day6 new solution1Part1) at: 2) = 6169101504608)
	
	
	
	
	
	

]

{ #category : 'tests' }
AOC2025Day6Test >> testSolution1Part2 [
	self assert: (AOC2025Day6 new solution1Part2 = 10442203393132)
	
	

]

{ #category : 'tests' }
AOC2025Day6Test >> testSolution2Part1 [
	self assert: (((AOC2025Day6 new solution2Part1) at: 2) = 6169101504608)
	
	
	
	
	
	

]
