"
```language=Pharo
""your comment goes here""
```

AOC2015Day1 is class name since all classes live in the global scope
AdventCode is the package name 

AOC2015Day1 input 
a class side method to return pattern of '()()()()()'




"
Class {
	#name : 'AOC2015Day7',
	#superclass : 'Object',
	#category : 'AdventCode',
	#package : 'AdventCode'
}

{ #category : 'accessing' }
AOC2015Day7 >> puzzleInput [ 
^ ''.

]

{ #category : 'as yet unclassified' }
AOC2015Day7 >> puzzleInputParsed [
	"parsed input goes here"
	^ self notYetImplemented 
	
	
]

{ #category : 'as yet unclassified' }
AOC2015Day7 >> puzzlePart1 [	
^ ' 
'

]

{ #category : 'as yet unclassified' }
AOC2015Day7 >> puzzlePart2 [	
^ ' 

'

]

{ #category : 'as yet unclassified' }
AOC2015Day7 >> solution1Part1 [

	^ self notYetImplemented
]

{ #category : 'as yet unclassified' }
AOC2015Day7 >> solution1Part2 [

	^ self notYetImplemented
]
