"
```language=Pharo
""your comment goes here""
```

AOC2015Day1 is class name since all classes live in the global scope
AdventCode is the package name 

AOC2015Day1 input 
a class side method to return pattern of '()()()()()'




"
Class {
	#name : 'AOC2015DayTemplate',
	#superclass : 'Object',
	#category : 'AdventCode2015',
	#package : 'AdventCode2015'
}

{ #category : 'accessing' }
AOC2015DayTemplate >> puzzleInput [ 
^ ''.

]

{ #category : 'as yet unclassified' }
AOC2015DayTemplate >> puzzleInputParsed [
	"parsed input goes here"
	^ self notYetImplemented 
	
	
]

{ #category : 'as yet unclassified' }
AOC2015DayTemplate >> puzzlePart1 [	
^ ' 
'

]

{ #category : 'as yet unclassified' }
AOC2015DayTemplate >> puzzlePart2 [	
^ ' 

'

]

{ #category : 'as yet unclassified' }
AOC2015DayTemplate >> solution1Part1 [

	^ self notYetImplemented
]

{ #category : 'as yet unclassified' }
AOC2015DayTemplate >> solution1Part2 [

	^ self notYetImplemented
]
