Class {
	#name : 'AOC2015DayTestTemplate',
	#superclass : 'TestCase',
	#category : 'Advent-Of-Code-2015',
	#package : 'Advent-Of-Code-2015'
}

{ #category : 'tests' }
AOC2015DayTestTemplate >> testSolution1Part1 [
	"self assert: (AOC2015Day5 new solution1Part1 = 280)  description: 'expect 280 answer'"
	self notYetImplemented 
	
	
	

]

{ #category : 'tests' }
AOC2015DayTestTemplate >> testSolution1Part2 [
	"self assert: (AOC2015Day5 new solution1Part2 = 1797)  description: 'expect 1797 answer'"
	self notYetImplemented 
	
	
	
	

]
