
Containers-Array2D
To load containers package use

Metacello new
  baseline: 'ContainersArray2D';
  repository: 'github://pharo-containers/Containers-Array2D/src';
  load.

If you need to depend on containers array 2d baseline you can use the spec

spec 
    baseline: 'ContainersArray2D' 
    with: [ spec repository: 'github://pharo-containers/Containers-Array2D/src' ].


Ok so do we have any examples

example 1


example 2

example 3


example 4

example 5


